INSERT INTO car (model_name, type) VALUES
('Fiat Panda', 'city'),
('Toyota Yaris', 'hybrid'),
('Ford Fiesta', 'hatchback'),
('BMW X1', 'SUV'),
('Audi A3', 'compact'),
('Volkswagen Golf', 'hatchback'),
('Peugeot 208', 'city'),
('Renault Clio', 'city'),
('Mercedes A-Class', 'premium'),
('Hyundai i10', 'city'),
('Kia Sportage', 'SUV'),
('Nissan Qashqai', 'SUV'),
('Dacia Duster', 'SUV'),
('Jeep Renegade', 'SUV'),
('Opel Corsa', 'city'),
('Skoda Fabia', 'compact'),
('Citroen C3', 'hatchback'),
('Mazda CX-3', 'crossover'),
('Honda Civic', 'sedan'),
('Subaru Impreza', 'AWD'),
('Tesla Model 3', 'electric'),
('Alfa Romeo Giulia', 'sedan'),
('Volvo XC40', 'SUV');
